### ISSUE TITLE
Crítica do campo data final vazia - operação ALT (alteração) do R1000

### ISSUE THREAD

**Issue by adrianocesarstm** [nfephp-org/sped-efdreinf#102]
Boa tarde,

Sou analista judiciário e trabalho no projeto efd-reinf no Superior Tribunal Militar. Estamos utilizando esse projeto para construção das mensagens XML a serem enviadas para a Receita Federal. Recentemente, notei que parece haver um bug na alteração do evento R1000. 
No arquivo https://github.com/nfephp-org/sped-efdreinf/blob/master/src/Factories/EvtInfoContri.php, na linha 88, é gerada uma exceção caso a mensagem seja ALT para evento R1000 possua o campo data final nulo. Nos nossos testes, enviamos um evento INC do R1000 passando a data inicial = '2022-04' e sem a data final.  Para enviar a operação ALT de R1000 para o referido evento, precisamos enviar a data inicial = '2022-04' e sem a data final (exatamente como a original, para identificar o evento), e nos campos nova data inicial e nova data final, os valores novos, no meu exemplo, passei nova_data_inicial = '2022-04' e nova_data_final = '2022-07'.
O "if" que gera a exception citada, a meu ver, deve ser removido.

**Comment by robmachado** [comment]
Vou verificar !!! Grato pela ajuda

**Comment by adrianocesarstm** [comment]
Olá, há alguma previsão de quando será liberada tag com esta correção?

**Comment by robmachado** [comment]
Já está no repositório dev-master

Quanto a tag stable vou ver se consigo subir apenas essa alteração

**Comment by adrianocesarstm** [comment]
Olá, estamos com previsão de colocar em produção nossa solução do reinf, na próxima semana. Poderia ser gerada a nova tag com a correção pontual?

**Comment by robmachado** [comment]
Neste fim de semana eu atualizo
