### ISSUE TITLE
envioLoteEventos 

### ISSUE THREAD

**Issue by 4letnis** [nfephp-org/sped-efdreinf#111]
Boa tarde Roberto. Estou desenvolvendo um programa semelhante em C# para envio do REINF, porém não estou conseguindo enviar os eventos em lote (http://www.reinf.esocial.gov.br/schemas/envioLoteEventosAssincrono/v1_00_00). 
Você consegue fazer o envio de XML para esse serviço? Poderia me enviar um exemplo de XML?
Obrigado!!

**Comment by robmachado** [comment]
Colega ! você está tendo o cuidado de mandar apenas eventos do mesmo tipo no seu lote ??

**Comment by robmachado** [comment]
Eu não tenho exemplos disponíveis de envio em lote com mais de um evento, pois normalmente, faço envios um a um, evento por evento, para facilitar o processamento no retorno.

**Comment by robmachado** [comment]
E mais eu ainda não implementei o envio de LOTE ASSINCRONO usando a API REST deles

**Comment by 4letnis** [comment]
Entendi, sem problemas, obrigado Roberto!

**Comment by robmachado** [comment]
Você pode fazer testes usando o SOAPUI, ele ajuda muito e talvez até o POSTMAN funcione

**Comment by robmachado** [comment]
O XML deve ser algo assim 

<?xml version=”1.0″ encoding=”UTF-8″?>
<Reinf xmlns=”[http://www.reinf.esocial.gov.br/schemas/envioLoteEventosAssincrono/v1_00_00″&gt](http://www.reinf.esocial.gov.br/schemas/envioLoteEventosAssincrono/v1_00_00%E2%80%B3&gt);
    <envioLoteEventos>
      <ideContribuinte>
        <tpInsc>1</tpInsc>
        <nrInsc>00000000</nrInsc>
      </ideContribuinte>
      <eventos>
        <evento Id=”ID0000000000000000000000000000000000″>
          <Reinf xmlns=”[http://www.reinf.esocial.gov.br/schemas/evt4099FechamentoDirf/v2_01_01″&gt](http://www.reinf.esocial.gov.br/schemas/evt4099FechamentoDirf/v2_01_01%E2%80%B3&gt);
            <evtFech id=”ID0000000000000000000000000000000000″>
              …
            </evtFech>
            <Signature xmlns=”[http://www.w3.org/2000/09/xmldsig#”&gt](https://www.w3.org/2000/09/xmldsig#%E2%80%9D&gt);
              ….
            </Signature>
          </Reinf>
        </evento>
      </eventos>
    </envioLoteEventos>
</Reinf>

**Comment by 4letnis** [comment]
Cara, meu problema era que tinha algum caractere especial oculto na tag tpInsc ... achei colocando num validador que bate o XML com o XSD ... o serviço tava me retornando algo tipo "serviço indisponivel, entre em contato...."  hahaha mas obrigado pela atenção!!
