### ISSUE TITLE
A data na factory não esta sendo atribuida

### ISSUE THREAD

**Issue by Tom4ate** [nfephp-org/sped-efdreinf#132]
Bom Dia! Estou realizando o cadastro de um novo evento R-1000 no layout V2, mas me deparei com uma situação em que a data de geração deveria ser anterior a data real e o parametro data não estava sendo levado em consideração.

Verificando na classe Common/Factory, no __construct, o parametro da $date não esta sendo atribuido, existe um comentario dizendo que é para proposito de DEBUG, seria possivel alterar isso para utilizar o parametro?

[Common/Factory](https://github.com/nfephp-org/sped-efdreinf/blob/master/src/Common/Factory.php)  

Posteriormente, na geração do id existe uma verificação da presença do date, mas sempre será nulo.

**Comment by robmachado** [comment]
Ajustado

**Comment by Tom4ate** [comment]
@robmachado  Muito obrigado pela resposta agil!
