### ISSUE TITLE
Problema no método Tools->getIdFromXml, não está identificando o grupo do evento corretamente

### ISSUE THREAD

**Issue by gabrielcarvalhohardness** [nfephp-org/sped-efdreinf#173]
Ao gerar um evento R-2010 e tentar transmiti-lo utilizando o método **enviaLoteXmlAssincrono**, está lançando uma exceção, só que estou informando o grupo correto, segue trecho do código.

~~~php
 $xml = Event::evtServTom($configJson, $std, $certificate)->toXml();
 $axml[] = $xml;

 $response = $tools->enviaLoteXmlAssincrono($tools::EVT_PERIODICOS, $axml);
~~~
 
Resultado:
~~~sh
Exception O grupo correto deve ser declarado e não pode diferirdo grupo dos eventos
~~~

Pelo que identifiquei o mapeamento dos ids no método **getIdFromXml** está errado.

![image](https://github.com/nfephp-org/sped-efdreinf/assets/100845348/843bb0b0-a21f-441a-99d0-af3f0ebd1bf1)

Na classe ToolsBase o mapeamento dos grupos está da seguinte maneira

![image](https://github.com/nfephp-org/sped-efdreinf/assets/100845348/58551edd-bc6f-499a-9ae4-c2d59fbb7f09)

**Comment by robmachado** [comment]
Deve estar corrigido em dev-master
