### ISSUE TITLE
Guia de utilização + EvtPgtosDivs (R-2070) em 2019

### ISSUE THREAD

**Issue by icaroscherma** [nfephp-org/sped-efdreinf#70]
Não estou encontrando algum guia sobre a biblioteca (EFD-ReInf em específico) ou sobre a transmissão desse evento (R-2070) em específico, não me refiro à como clonar ou fazer coisas de php/composer ou organização de projetos, mas à um "fluxo obrigatório" ou guia/pacote de informações/validações necessários para que o pacote seja validado e enviado.

Sobre o evento R-2070, vi que até a versão 1.03.02 esta biblioteca possuía o factory e schemes, mas na 1.04 ele tem somente o Fake (talvez por ter sido suspenso até o fim de 2018).

Após algumas pesquisas, vi que o fluxo poderia ser como:

1. Puxar tabelas de referência da Receita/Fazenda
2. Cadastrar informações da empresa (R-1000)
3. Cadastrar evento periódio (período do grupo de itens a ser enviado) (R-1070)
4. Cadastrar ítens (NFe) nesse período (R-2070)
5. Fechar o período transmitindo pra receita o que foi feito. (R-1070)

(Os eventos posteriores como correção e re-envio seriam opcionais)

Imagens de guia:
![image](https://user-images.githubusercontent.com/42467/55489184-d46a3200-5607-11e9-827d-88278a5a4ae8.png)

**Comment by robmachado** [comment]
Então o evento R-2070 não existe mais na versão 1.4, [vide layouts dos eventos](http://sped.rfb.gov.br/arquivo/show/2778). 
Foi esquecimento meu não ter removido dos exemplos.

Denominado "R-2070 - Retenções na Fonte - IR, CSLL, COFINS, PIS/PASEP",  Existia no leiaute 1.3.02 da Reinf e tinha previsão de ser disponibilizado junto com o 2º grupo  em 11/2018. 
Porém a receita federal , alterou a entrega do segundo grupo de 11/2018 para 01/01/2019 , e retirou do leiaute 1.4 ( mais recente)  o evento 2070. 

Na prática:

Não há previsão de entrega do registro R-2070, tendo em vista que a receita o retirou do manual de orientações e assim a DIRF 2019 será entregue normalmente com as informações de retenções.

O 1º grupo foi as empresas que tiveram faturamento superior a 78 milhões , o 2º grupo será os demais entidades empresarias . 

As empresas precisam se atentar se tem movimentação no período. Exemplo: As empresa se enquadra no 2º grupo mas no período ativo não tem INSS retido, CPRB, ou e não é Produtor Rural obrigada à gerar o registro 2050. 

Então deverá enviar apenas o encerramento .
