### ISSUE TITLE
Retorno retornoRecibosChaveEvento-v1_05_01.xsd

### ISSUE THREAD

**Issue by jesserovira** [nfephp-org/sped-efdreinf#92]
Prezados,

qual consulta ou qual método que produz esse retorno? Preciso recuperar o recibo e protocolo, mas não consigo obter esse resulta do XSD nos metodos que estou utilizando.

Aguardo, grato pelo apoio.

**Comment by robmachado** [comment]
Todas as consultas disponíveis estão exemplificadas nos exemplos, para melhor entendimento leia a documentação da Receita

**Comment by robmachado** [comment]
Acredito que esse retorno seja referente ao item f na página 33 do manual

f) Recuperação do RECIBO DE ENTREGA do evento.

**Comment by jesserovira** [comment]
Rob, obrigado pelo retorno. Aqui, chance de abusar da sua boa vontade, mas qual manual? Eu to realmente bem perdido. Ja li varias documentações, e não to evoluindo.

**Comment by jesserovira** [comment]
Porque no caso do retorno do evento de envio, o que recebi foi o seguinte:

"{
    \"ReceberLoteEventosResponse\": {
        \"ReceberLoteEventosResult\": {
            \"Reinf\": {
                \"retornoLoteEventos\": {
                    \"@attributes\": {
                        \"id\": \"ID77C54070256B2C12662E74608C45A28C\"
                    },
                    \"ideTransmissor\": {
                        \"IdTransmissor\": \"25499614000190\"
                    },
                    \"status\": {
                        \"cdStatus\": \"0\",
                        \"descRetorno\": \"SUCESSO\"
                    },
                    \"retornoEventos\": {
                        \"evento\": {
                            \"@attributes\": {
                                \"id\": \"ID1254996140000002022021315352600008\"
                            },
                            \"Reinf\": {
                                \"evtTotal\": {
                                    \"@attributes\": {
                                        \"id\": \"ID2103686649\"
                                    },
                                    \"ideEvento\": {
                                        \"perApur\": []
                                    },
                                    \"ideContri\": {
                                        \"tpInsc\": \"1\",
                                        \"nrInsc\": \"25499614\"
                                    },
                                    \"ideRecRetorno\": {
                                        \"ideStatus\": {
                                            \"cdRetorno\": \"0\",
                                            \"descRetorno\": \"SUCESSO\"
                                        }
                                    },
                                    \"infoRecEv\": {
                                        \"dhProcess\": \"2022-02-13T15:35:27.3625343-03:00\",
                                        \"tpEv\": \"1000\",
                                        \"idEv\": \"ID1254996140000002022021315352600008\",
                                        \"hash\": \"x6oWiZkCRKwqJe\\\/9okIOcg6QTzh7\\\/xKrHJGmh7YhgxY=\"
                                    },
                                    \"infoTotal\": {
                                        \"nrRecArqBase\": \"82850-04-1000-2202-82850\"
                                    }
                                },
                                \"Signature\": {
                                    \"SignedInfo\": {
                                        \"CanonicalizationMethod\": {
                                            \"@attributes\": {
                                                \"Algorithm\": \"http:\\\/\\\/www.w3.org\\\/TR\\\/2001\\\/REC-xml-c14n-20010315\"
                                            }
                                        },
                                        \"SignatureMethod\": {
                                            \"@attributes\": {
                                                \"Algorithm\": \"http:\\\/\\\/www.w3.org\\\/2001\\\/04\\\/xmldsig-more#rsa-sha256\"
                                            }
                                        },
                                        \"Reference\": {
                                            \"@attributes\": {
                                                \"URI\": \"#ID2103686649\"
                                            },
                                            \"Transforms\": {
                                                \"Transform\": [
                                                    {
                                                        \"@attributes\": {
                                                            \"Algorithm\": \"http:\\\/\\\/www.w3.org\\\/2000\\\/09\\\/xmldsig#enveloped-signature\"
                                                        }
                                                    },
                                                    {
                                                        \"@attributes\": {
                                                            \"Algorithm\": \"http:\\\/\\\/www.w3.org\\\/TR\\\/2001\\\/REC-xml-c14n-20010315\"
                                                        }
                                                    }
                                                ]
                                            },
                                            \"DigestMethod\": {
                                                \"@attributes\": {
                                                    \"Algorithm\": \"http:\\\/\\\/www.w3.org\\\/2001\\\/04\\\/xmlenc#sha256\"
                                                }
                                            },
                                            \"DigestValue\": \"CW4kBJw0H5y5wyhDv68AxHZ1muMUhic3vDUtU4SJkTs=\"
                                        }
                                    },
                                    \"SignatureValue\": \"eLBKnGhk739P0MiZ6RaEU29TIVR1unEb0LZs7mzADVn78eygvZMNYAYRMvkM5Nv+jJ7sCTUqcIMeCYjTmrHxIN6QTnWgifOsdv9lxZH7t0vzzW8CMdR0FWZZXOux5gtmdiRWpUvMNWBQI1qxRmili+4qxl3s463p5Z8i4uyaD+T5Inhg\\\/rDLDd0\\\/CGyf8PyRmaTaKHgiLpxx4xjy5Np3Y4D\\\/raMcBmbuZt1lhWMI130NnEcV1PcdLe\\\/XKO1DVbLy3mInv\\\/lT9JXlS8eqeBW147A7+PXspaqGCfWnenM88NePjLXXDCX5a+JbbDeJrjmhAkyjn9cLPTyNp6xvlkIFYg==\",
                                    \"KeyInfo\": {
                                        \"X509Data\": {
                                            \"X509Certificate\": \"MIIHwTCCBamgAwIBAgINAN\\\/ChxxcMb4T40uEMjANBgkqhkiG9w0BAQsFADCBpzELMAkGA1UEBhMCQlIxEzARBgNVBAoMCklDUC1CcmFzaWwxDzANBgNVBAsMBkNTUEItMTE7MDkGA1UECwwyU2VydmljbyBGZWRlcmFsIGRlIFByb2Nlc3NhbWVudG8gZGUgRGFkb3MgLSBTRVJQUk8xNTAzBgNVBAMMLEF1dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBkbyBTRVJQUk8gRmluYWwgU1NMMB4XDTIxMDgxMTE4MTUyNloXDTIyMDgxMTE4MTUyNlowgeMxCzAJBgNVBAYTAkJSMRMwEQYDVQQKDApJQ1AtQnJhc2lsMRkwFwYDVQQLDBB2aWRlb2NvbmZlcmVuY2lhMRcwFQYDVQQLDA4zMzY4MzExMTAwMDEwNzEVMBMGA1UECwwMQXBsaWNhY2FvIEExMREwDwYDVQQLDAhBUlNFUlBSTzE1MDMGA1UECwwsQXV0b3JpZGFkZSBDZXJ0aWZpY2Fkb3JhIGRvIFNFUlBSTyBGaW5hbCBTU0wxKjAoBgNVBAMMIUFQUDEwMTU1LlBSRVBST0RVQ0FPLlJFSU5GLkdPVi5CUjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAN5ulgaM7hJkmW94YgSWkUKfM9potdETVgxP8ziPPAA7RWkzt2UnpH7Zpu9bpUFD3kIt8wJI51lIwg5chtt7MQsDYuyimE\\\/uAaqSszw0c6a0yYsXAZCpb2RKscPqnxjdJOwtmqRESnU1PHTTV1IlkROgpp1S1BdB2P9amL+V+nPpoLah\\\/VsQ4KZmaR1PAl+wIwmFq1EfizqzKVQA\\\/9w2soIyI\\\/c918aSK81K0pKS6tuAojJxU9fPOBHtuGKn4L4MM1KL9qNY\\\/rH3TOhn\\\/fEJU1UtVKkc39KPxJ3Tdwb7sV\\\/NgdjlzKEr+YlWhdJG9gd1AbTm0H4TeaNTxr34UKJ2SgMCAwEAAaOCAqwwggKoMB8GA1UdIwQYMBaAFN0IWX5OFh0j0lSCvVxUh2TD+gM\\\/MIGLBgNVHR8EgYMwgYAwPaA7oDmGN2h0dHA6Ly9yZXBvc2l0b3Jpby5zZXJwcm8uZ292LmJyL2xjci9hY3NlcnByb2FjZnNzbC5jcmwwP6A9oDuGOWh0dHA6Ly9jZXJ0aWZpY2Fkb3MyLnNlcnByby5nb3YuYnIvbGNyL2Fjc2VycHJvYWNmc3NsLmNybDCBjgYIKwYBBQUHAQEEgYEwfzBHBggrBgEFBQcwAoY7aHR0cDovL3JlcG9zaXRvcmlvLnNlcnByby5nb3YuYnIvY2FkZWlhcy9hY3NlcnByb2FjZnNzbC5wN2IwNAYIKwYBBQUHMAGGKGh0dHA6Ly9vY3NwLnNlcnByby5nb3YuYnIvQUNTRVJQUk9BQ0ZTU0wwgeAGA1UdEQSB2DCB1aA7BgVgTAEDCKAyBDBTRVJWSUNPIEZFREVSQUwgREUgUFJPQ0VTU0FNRU5UTyBERSBEQURPUyBTRVJQUk+gGQYFYEwBAwOgEAQOMzM2ODMxMTEwMDAxMDegIgYFYEwBAwKgGQQXRURVQVJETyBZT1NISURBIFNBTE9NQU+gOAYFYEwBAwSgLwQtMTgwMzE5ODAyODU2MDE2ODgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwgR1lZHVhcmRvLnlvc2hpZGFAc2VycHJvLmdvdi5icjAOBgNVHQ8BAf8EBAMCBeAwEwYDVR0lBAwwCgYIKwYBBQUHAwIwXgYDVR0gBFcwVTBTBgZgTAECAVkwSTBHBggrBgEFBQcCARY7aHR0cDovL3JlcG9zaXRvcmlvLnNlcnByby5nb3YuYnIvZG9jcy9kcGNhY3NlcnByb2FjZnNzbC5wZGYwDQYJKoZIhvcNAQELBQADggIBADxAIu\\\/97yGPhEUoa3r1r6XWcn3upl6lJSglNoDpmYgYqREm7ODZqxbsQB6V2cMU+uX9Eresxpw8100x2vQQgTmqcHWCEHewuqZ7TlCWPbBm6eQNKg0bMexNtpyJEDilepGuLkSs1M5JGTLfehqLXO0yazqJFsBf2Qtzz3GQeDXlTTReYoikloG57R5Oo+6\\\/rdvx0fh\\\/pcU02w1WfaZYsXZYLTGjQMdWFHJGXIsXJe6OOZACF27kW23knKb1sSamS\\\/IXiEC2Bp0IjUFkxBK8sRX0jEWFTBUPAXFdooRIPQH7DXWkODqP7yv\\\/SSAf2OAGeJVbknoR61lGmrS3f0sq7dB6H\\\/1cfffj5o8BXCtjB17NuOg+v11ERrDwnc3djqVwOd2i9oolZjyqtQs0VELlCBnn8p538JoXTTz47Luag3kInJD8kcfgJygjQ0Fq\\\/DcBXzrE5caRM1waL9KwvfeISnBsbuCDSqsBjWV8GHPYyzQR1vpE76Fh45uF9Oa6RO3dzqhuOJNE5sr15vf6yS\\\/b0JOji8b89xhkWDqwJojAW\\\/YQQlwNeHSTkv2DYaFX60x5571t\\\/oVwAy+AR3Vq8g+sD57zZ7uwx9mzI8U\\\/V3cf1Ty2eXaOPaUl7s\\\/KZ6h+l3VjYl60s2sU8Khunt2X4ze04YSS4VPoigPhYTqdNwmfD16W\"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}"

**Comment by jesserovira** [comment]
A partir desse retorno, eu pensei que tivesse que consultar o evento de forma isolada, na consulta do evento, e o resultado foi o seguinte:

{"ConsultaReciboEvento1000Response":{"ConsultaReciboEvento1000Result":{"Reinf":{"ideStatus":{"cdRetorno":"1","descRetorno":"Um ou mais eventos encontrados"},"retornoEventos":{"evento":{"iniValid":"2022-01"}}}}}}  

Ou seja, nem o metodo de envio, nem o retorno da consulta, produziram o retorno que está especificado naquele XSD.

Grato
