### ISSUE TITLE
Gerar tag v1.0.2 contendo a correção da última issue fechada (issue #96).

### ISSUE THREAD

**Issue by gabrielst1984** [nfephp-org/sped-efdreinf#98]
Gerar tag v1.0.2 contendo a correção da última issue fechada (issue #96).

**Comment by robmachado** [comment]
Não entendi absolutamente nada !!

**Comment by gabrielst1984** [comment]
git tag para possibilitar referenciar a versão específica no composer.json do projeto que depende dessa biblioteca, sem necessariamente obter a versão mais atualizada que está na master.

**Comment by robmachado** [comment]
Agora entendi você está pedindo para gerar uma RELEASE (tag) !! ok
